project_id = "clvafviwuzpjvmthrcpf"

[auth.email.smtp]
enabled = true
host = "smtp.resend.com"
port = 465
user = "resend"
pass = "env(RESEND_API_KEY)"
admin_email = "support@ezsignnow.com"
sender_name = "EZSignNow"