project_id = "clvafviwuzpjvmthrcpf"

[auth.email.smtp]
enabled = true
host = "smtppro.zoho.com"
port = 587
user = "support@ezsignnow.com"
pass = "Techl@der@2023"
admin_email = "support@ezsignnow.com"
sender_name = "EZSignNow"